@Samurai.Api_HostAddress = https://localhost:7072/api

GET {{Samurai.Api_HostAddress}}/Samurai/
Accept: application/json

###


POST {{Samurai.Api_HostAddress}}/Samurai/
Content-Type: application/json

{
  "Name": "John",
  "Description": "A Samurai Jack",
  "Age": 29

}